### ISSUE TITLE
TypeError: _detect_vcs() missing 2 required positional arguments: 'expected_vcs' and 'path'

### ISSUE THREAD

**Issue by pengpengyang94** [YangLabHKUST/STitch3D#25]
I installed the stitch3d package using conda, following the provided instructions. However, when importing stitch3d, I am getting a TypeError. How can I troubleshoot this issue?

**Comment by gefeiwang** [comment]
Hi there, 

Thank you for your interest in our package. This error seems to arise from one of the package dependencies. Could you provide a complete error report so we can find the source of the issue? Besides using conda, you can also try `pip install stitch3d` for installation.

Best,
Gefei

**Comment by pengpengyang94** [comment]
> Hi there,
> 
> Thank you for your interest in our package. This error seems to arise from one of the package dependencies. Could you provide a complete error report so we can find the source of the issue? Besides using conda, you can also try `pip install stitch3d` for installation.
> 
> Best, Gefei

Attached is the full error report. Upon inspection, it appears the issue may be caused by an incompatibility with the scanpy package.

```>>> import STitch3D
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data3/yangpp/soft/STitch3D/STitch3D/__init__.py", line 1, in <module>
    import STitch3D.utils
  File "/data3/yangpp/soft/STitch3D/STitch3D/utils.py", line 2, in <module>
    import scanpy as sc
  File "/data/anaconda3/envs/stitch3d/lib/python3.9/site-packages/scanpy/__init__.py", line 18, in <module>
    from . import datasets, logging, queries, external, get
  File "/data/anaconda3/envs/stitch3d/lib/python3.9/site-packages/scanpy/external/__init__.py", line 3, in <module>
    from . import pp
  File "/data/anaconda3/envs/stitch3d/lib/python3.9/site-packages/scanpy/external/pp/__init__.py", line 5, in <module>
    from ._magic import magic
  File "/data/anaconda3/envs/stitch3d/lib/python3.9/site-packages/scanpy/external/pp/_magic.py", line 7, in <module>
    from legacy_api_wrap import legacy_api
  File "/data/anaconda3/envs/stitch3d/lib/python3.9/site-packages/legacy_api_wrap.py", line 18, in <module>
    from get_version import get_version
  File "/data/anaconda3/envs/stitch3d/lib/python3.9/site-packages/get_version/__init__.py", line 287, in <module>
    __version__ = get_version(__file__)
  File "/data/anaconda3/envs/stitch3d/lib/python3.9/site-packages/get_version/__init__.py", line 270, in get_version
    version = method(parent)
  File "/data/anaconda3/envs/stitch3d/lib/python3.9/site-packages/get_version/__init__.py", line 117, in get_version_from_vcs
    vcs_root = find_vcs_root(parent, vcs=vcs)
  File "/data/anaconda3/envs/stitch3d/lib/python3.9/site-packages/get_version/__init__.py", line 148, in find_vcs_root
    vcs_e = _detect_vcs()
TypeError: _detect_vcs() missing 2 required positional arguments: 'expected_vcs' and 'path'
```

**Comment by pengpengyang94** [comment]
> Hi there,
> 
> Thank you for your interest in our package. This error seems to arise from one of the package dependencies. Could you provide a complete error report so we can find the source of the issue? Besides using conda, you can also try `pip install stitch3d` for installation.
> 
> Best, Gefei

Installation via pip also produced errors. Therefore, I opted to use conda install instead.

**Comment by gefeiwang** [comment]
May I know which version of scanpy you are using?

**Comment by gefeiwang** [comment]
The scanpy version you installed has a conflict with other packages in your environment. 

The error occurs when it tries to call `from legacy_api_wrap import legacy_api` in module `scanpy/external/pp/_magic.py`. This command has been deleted in [an update for scanpy](https://github.com/scverse/scanpy/commit/1be40918a39aa11e27c1ccd97253636784f4b8d4) on June 29, 2021, so updating your scanpy to a newer version (e.g. 1.8.1 or later) might be helpful.

**Comment by pengpengyang94** [comment]
> May I know which version of scanpy you are using?
The software dependencies list indicates the installed version of the scanpy package.
```
$pip show scanpy
Name: scanpy
Version: 1.7.2
```

**Comment by pengpengyang94** [comment]
> The scanpy version you installed has a conflict with other packages in your environment.
> 
> The error occurs when it tries to call `from legacy_api_wrap import legacy_api` in module `scanpy/external/pp/_magic.py`. This command has been deleted in [an update for scanpy](https://github.com/scverse/scanpy/commit/1be40918a39aa11e27c1ccd97253636784f4b8d4) on June 29, 2021, so updating your scanpy to a newer version (e.g. 1.8.1 or later) might be helpful.

Following your recommendations resolved the issue. Thank you very much for your assistance.

```
pip install scanpy==1.8.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
```
