### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by summus-kong** [YangLabHKUST/STitch3D#26]
Dear professor,
When I install STich3D using conda, an error was occured as below, how can i solve it? Thank you!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/wbhou/.local/lib/python3.8/site-packages/STitch3D/__init__.py", line 1, in <module>
    import STitch3D.utils
  File "/public/home/wbhou/.local/lib/python3.8/site-packages/STitch3D/utils.py", line 2, in <module>
    import scanpy as sc
  File "/public/home/wbhou/.local/lib/python3.8/site-packages/scanpy/__init__.py", line 18, in <module>
    from . import datasets, logging, queries, external, get
  File "/public/home/wbhou/.local/lib/python3.8/site-packages/scanpy/external/__init__.py", line 3, in <module>
    from . import pp
  File "/public/home/wbhou/.local/lib/python3.8/site-packages/scanpy/external/pp/__init__.py", line 5, in <module>
    from ._magic import magic
  File "/public/home/wbhou/.local/lib/python3.8/site-packages/scanpy/external/pp/_magic.py", line 7, in <module>
    from legacy_api_wrap import legacy_api
  File "/public/home/wbhou/.local/lib/python3.8/site-packages/legacy_api_wrap.py", line 21, in <module>
    __version__ = get_version(__file__)
  File "/public/home/wbhou/.local/lib/python3.8/site-packages/get_version/__init__.py", line 273, in get_version
    version = method(parent)
  File "/public/home/wbhou/.local/lib/python3.8/site-packages/get_version/__init__.py", line 118, in get_version_from_vcs
    vcs_root = find_vcs_root(parent, vcs=vcs)
  File "/public/home/wbhou/.local/lib/python3.8/site-packages/get_version/__init__.py", line 151, in find_vcs_root
    vcs_e = _detect_vcs()
TypeError: _detect_vcs() missing 2 required positional arguments: 'expected_vcs' and 'path'

**Comment by gefeiwang** [comment]
Hi there,

please if the solution here can help you solve the issue or not: https://github.com/YangLabHKUST/STitch3D/issues/25.

Best,
Gefei

**Comment by summus-kong** [comment]
Dear Professor Geifei,

Got it! Thanks for your explanation! Very appreciated!

Best regards,
Summus

**Comment by summus-kong** [comment]
Dear Professor Geifei,

Got it! Thanks for your explanation! Very appreciated! 

Best regards,
Cristal

**Comment by summus-kong** [comment]
Dear Professor Geifei,

Got it! Thanks for your explanation! Very appreciated!

Best regards,
Summus
